# Programa Ingenias+ Data Science

Como dijimos en clases anteriores, Python tiene implementadas muchas librerias para poder trabajar con datos. En la clase de hoy trabajaremos con una de ellas: `Numpy`.

Antes de comenzar, vamos a hablar un poco de esta libreria o modulo.

**Numpy** es una librería optimizada para realizar cálculos numéricos con vectores y matrices. A diferencia de otros lenguajes de programación, Python no posee en su estructura central la figura de matrices. Eso quiere decir que para poder trabajar con esta estructura de datos deberiamos trabajar con listas de listas. NumPy introduce el concepto de arrays o matrices.

Al ser de código abierto, `numpy` posee una documentación muy amplia que es **SIEMPRE RECOMENDABLE** consultar.

- [Documentacion NumPy](https://devdocs.io/numpy/)

## Clase 4: Introduccion a NumPy

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [1]:
import numpy as np

In [2]:
#1. Crear un arreglo de ceros de longitud 12
arr1 = np.zeros(12)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
#Creo un arreglo de 10 ceros, especificando que sean de tipo número entero
arr2 = np.zeros(10, int)
#Cambio el valor de la quinta posición (para Python, visiblemente es la sexta)
arr2[5] = 10
arr2

array([ 0,  0,  0,  0,  0, 10,  0,  0,  0,  0])

In [4]:
#3. Crear un arreglo que tenga los números del 10 al 49
arr3 = np.arange(10,50)
arr3

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [5]:
#4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
#Creo un arreglo de una dimensión con los números del 0 al 8 y luego le doy fomra de 2 dimesiones de 3x3
arr4 = np.arange(9).reshape(3,3)
arr4

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
#5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
#Creo un arreglo de 100 números enteros que varíen del 0 al 49
arr5 = np.random.randint(50, size=100)
print(arr5)
print(f'Media: {arr5.mean()}') #También es posible con np.mean(arr5)
print(f'Varianza: {arr5.var()}') #También es posible con np.var(arr5)

[38 41 23  6  8  7  2 25 12 29 11  4 19 18 33 45 15 48 17 43 22 38 49 11
 44 38 22  0  3 10 38 43 39 36 43 22 45  0  3 44 18 26  7 18 30  3 14 25
 37 30 14 41 20 10 19 39 45  5 17 38 39 10 28 43 38 33 11  2  1 17 47 16
 17 43 23  2 12 49 45 14  8  0  5 10 22 13 43  6 27  2  0 10 21 45 40 44
 32 24  1  5]
Media: 22.98
Varianza: 237.53960000000004


In [10]:
#6. Calcular la media de un arreglo usando np.sum
#Creo un arreglo de números aleatoreos entre 0 y 99, de longitud 10
arr6 = np.random.randint(0,100,10)
#Calculo la media como suma de todos los valores del arreglo (sum) divido la cantidad de elementos en el arreglo (size)
media = arr6.sum()/arr6.size
print(arr6)
#Imprimo la media calculada con sum y la media con numpy para comparar
print(f'Media: {media} - np.mean: {np.mean(arr6)}')

[78 67 25 92 87 52  5  2 73 44]
Media: 52.5 - np.mean: 52.5


In [11]:
#7. Calcular la varianza de un arreglo usando np.sum y np.mean
#Creo un arreglo de números aleatoreos entre 0 y 29, de longitud 10
arr7 = np.random.randint(0,30,10)
#Calculo la media del arreglo y lo guardo en la variable 'media'
media = np.mean(arr7)
#Calculo, y almaceno en variable 'var', la varizanza como: 
# la suma (np.sum) del cuadrado (**2) de la diferencia de cada elemento del arreglo con su media (arr7 - media)
# divido la cantidad de elementos del arreglo (size)
var = np.sum((arr7 - media) ** 2)/arr7.size
#Muestro la varianza de la variable 'var' y la varianza calculada con numpy para comparar
print(f"Varianza calculada: {var} - np.var: {arr7.var()}")

Varianza calculada: 90.24 - np.var: 90.24


In [12]:
#8. Crear un array de números aleatorios usando np.random.randn
arr8 = np.random.randn(10)
arr8

array([ 0.29183558,  0.43654352,  0.30411994, -1.22859613,  0.49191263,
       -1.27083066, -0.59859925,  0.4580239 , -0.13044037,  1.07328334])